mp:
  messaging:
    incoming:
      /device/location:
        topic: location
        connector: smallrye-kafka
      /device/status:
        topic: status
        connector: smallrye-kafka
quarkus:
  kafka:
    devservices:
      port: 9092