version: 2
registries:
  container-redhat:
    type: docker-registry
    url: https://registry.redhat.io
    username: 16798353|github
    password: ${{secrets.REDHAT_REGISTRY_SECRET}}
updates:
  - package-ecosystem: "maven"
    directory: "/"
    open-pull-requests-limit: 3
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/backend/src/main/docker"
    open-pull-requests-limit: 1
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/device-registrar/src/main/docker"
    open-pull-requests-limit: 1
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/notification-dispatcher/src/main/docker"
    open-pull-requests-limit: 1
    schedule:
      interval: "weekly"
