---
schemaVersion: 2.3.0
metadata:
  name: cerebralstratum-backend
projects:
  - name: cerebralstratum-backend
    git:
      remotes:
        origin: https://github.com/blueguardian-co/cerebralstratum-backend.git
components:
  - name: workstation-container
    container:
      image: registry.redhat.io/devspaces/udi-rhel8:latest
      cpuLimit: "4.0"
      cpuRequest: 200m
      memoryLimit: 8Gi
      memoryRequest: 256Mi
      command:
        - sleep
        - infinity