schemaVersion: 2.2.0
metadata:
  name: cerebralstratum-backend
components:
  - attributes:
      controller.devfile.io/merge-contribution: true
    container:
      env:
        - name: CHE_DASHBOARD_URL
          value: https://devspaces.apps.sandbox-m4.g2pi.p1.openshiftapps.com
        - name: CHE_PLUGIN_REGISTRY_URL
          value: https://devspaces.apps.sandbox-m4.g2pi.p1.openshiftapps.com/plugin-registry/v3
        - name: CHE_PLUGIN_REGISTRY_INTERNAL_URL
          value: http://plugin-registry.crw.svc:8080/v3
        - name: CLUSTER_CONSOLE_URL
          value: https://console-openshift-console.apps.sandbox-m4.g2pi.p1.openshiftapps.com
        - name: CLUSTER_CONSOLE_TITLE
          value: OpenShift console
        - name: OPENVSX_REGISTRY_URL
          value: https://open-vsx.org
      image: registry.redhat.io/devspaces/udi-rhel8@sha256:d9467e83617e9ce7c76a5547894ef2fc3e5267af36da49573c2ff06b4c40bb51
      sourceMapping: /projects
    name: universal-developer-image
  - container:
      command:
        - sleep
        - infinity
      env:
        - name: DEV_MODE
          value: 'true'
      endpoints:
        - exposure: public
          name: csapi
          protocol: http
          targetPort: 6443
      mountSources: true
      sourceMapping: /projects
      image: registry.access.redhat.com/ubi9/openjdk-17-runtime:latest
    name: java
commands:
  - id: compile-and-run
    label: compile and run
    exec:
      component: java
      commandLine: './mvnw compile quarkus:dev'
      workingDir: '${PROJECTS_SOURCE}'
