[allowlist]
description = "Global Allowlist"

# Ignore based on any subset of the file path
paths = [
    # Ignore realm secrets used for dev
    '''src\/main\/resources\/devservices\/realm.json$''',
]