quarkus.smallrye-openapi.path=/openapi
quarkus.swagger-ui.path=/swagger-ui
quarkus.http.port=6443
quarkus.http.host=0.0.0.0
quarkus.http.cors=true
quarkus.http.cors.origins=http://workspace96483108444642e9-1.apps.sandbox-m4.g2pi.p1.openshiftapps.com