quarkus:
  application:
    name: cerebral-stratum-notification-dispatcher
  http:
    port: 6445
  devservices:
    enabled: true
  live-reload:
    instrumentation: true
  kafka:
    devservices:
      port: 9092

mp:
  messaging:
    incoming:
      /device/location:
        topic: location
        connector: smallrye-kafka
      /device/status:
        topic: status
        connector: smallrye-kafka

'%dev':
  quarkus:
    otel:
      resource:
        attributes: "service.instance.id=${HOSTNAME:unknown-dev},service.name=cerebral-stratum-notification-dispatcher,deployment.environment.name=development"
      traces:
        enabled: true
        eusp:
          enabled: true
      logs:
        enabled: true
      metrics:
        enabled: true
      exporter:
        otlp:
          endpoint: https://otlp-gateway-prod-au-southeast-1.grafana.net/otlp
          protocol: http/protobuf
          headers: ${QUARKUS_OTEL_EXPORTER_OTLP_HEADERS}

'%test':
  quarkus:
    otel:
      traces:
        enabled: false
      metrics:
        enabled: false
      logs:
        enabled: false

'%prod':
  quarkus:
    otel:
      resource:
        attributes: "service.instance.id=${HOSTNAME:unknown-prod},service.name=cerebral-stratum-notification-dispatcher,service.namespace=cerebral-stratum,deployment.environment.name=production"
      traces:
        enabled: true
        eusp:
          enabled: false
      metrics:
        enabled: true
      logs:
        enabled: true
    http:
      host: 0.0.0.0
    datasource:
      jdbc:
        url: ${JDBC_URL:jdbc:postgresql://localhost:5432/cerebral-stratum}
      username: ${JDBC_USERNAME:postgres}
      password: ${JDBC_PASSWORD}
