mp:
  messaging:
    outgoing:
      /device/location:
        topic: location
        host: ${MQTT_HOST:localhost}
        port: 1883
        connector: smallrye-mqtt
      /device/status:
        topic: status
        host: ${MQTT_HOST:localhost}
        port: 1883
        connector: smallrye-mqtt