quarkus:
#  devservices:
#    enabled: false
  smallrye-openapi:
    path: /openapi
  swagger-ui:
    path: /swagger-ui
    always-include: true
  http:
    port: 6443
    cors:
      ~: true
  dev-ui:
    cors:
      enabled: false
  live-reload:
    instrumentation: true
  datasource:
    db-kind: postgresql
    devservices:
      db-name: cerebral-stratum
      init-script-path: devservices/init.sql
      port: 5432
      image-name: docker.io/postgis/postgis:17-master
  hibernate-orm:
    database:
      default-schema: ${quarkus.liquibase.default-schema-name}
      generation: none
    mapping:
      timezone:
        default-storage: normalize-utc
  oidc:
    client-id: cerebral-stratum-backend
  keycloak:
    devservices:
      enabled: false
#      realm-path: devservices/realm.json
#      realm-name: external
#      port: 8000
#      start-command: >-
#        start-dev --http-enabled=true --proxy-headers=xforwarded --features=organization:v1
#      java-opts: >-
#        -XX:UseSVE=0
    policy-enforcer:
      enable: false
    admin-client:
      realm: ${keycloak.realm}
  scheduler:
    start-mode: normal
  kafka:
    devservices:
      port: 9092
'%prod':
  quarkus:
    liquibase:
      migrate-at-start: true
      change-log: db/changeLog.yaml
      default-schema-name: cerebralstratum
    http:
      host: 0.0.0.0
      cors:
        origins: /.*/
    kubernetes-config:
      secrets:
        ~:
          - db-creds
          - backend-oidc
        enabled: true
      secrets-role-config:
        name: cerebral-stratum-backend
    datasource:
      jdbc:
        url: ${jdbc-url}?defaultSchema=cerebralstratum
      username: ${jdbc-username}
      password: ${jdbc-password}
    oidc:
      auth-server-url: https://sso.blueguardian.co/realms/external
      credentials:
        secret: ${oidc-secret}
    keycloak:
      admin-client:
        server-url: https://sso.blueguardian.co
        username:
        password:
        realm: ${keycloak.realm}
        grant-type: CLIENT_CREDENTIALS
        client-id: ${quarkus.oidc.client-id}
        client-secret: ${quarkus.oidc.credentials.secret}
      policy-enforcer:
        enable: true
        paths:
          quarkus-status:
            paths: /q/*
            enforcement-mode: disabled
          swagger-ui:
            paths: /swagger-ui/*
            enforcement-mode: disabled
          openapi:
            paths: /openapi
            enforcement-mode: disabled
'%dev':
#  kafka:
#    bootstrap:
#      servers:
#        - kafka-cluster-kafka-bootstrap.development.svc.cluster.local:9092
#    security:
#      protocol: SASL_PLAINTEXT
#    sasl:
#      mechanism: PLAIN
#      jaas:
#        config: >-
#          org.apache.kafka.common.security.plain.PlainLoginModule required
#          username="${kafka-username}"
#          password="${kafka-password}";
  quarkus:
    liquibase:
      migrate-at-start: true
      change-log: devservices/changeLog.yaml
      default-schema-name: cerebralstratum
#    kubernetes-config:
#      secrets:
#        ~:
#          - db-creds
#          - oidc-creds
#          - message-bus-creds
#        enabled: true
    http:
      host: localhost
      cors:
        origins: /.*/
    oidc:
      auth-server-url: http://localhost:8000/realms/${keycloak.realm}
      credentials:
        secret: yxj6VJfZB8plW95iLkGn9ebWPPhic6yY
      client-id: cerebral-stratum-backend
    keycloak:
      admin-client:
        server-url: http://localhost:8000
        username:
        password:
        realm: ${keycloak.realm}
        grant-type: CLIENT_CREDENTIALS
        client-id: ${quarkus.oidc.client-id}
        client-secret: ${quarkus.oidc.credentials.secret}
#    datasource:
#      jdbc:
#        url: ${jdbc-url}?defaultSchema=cerebralstratum
#      username: ${jdbc-username}
#      password: ${jdbc-password}
mp:
 messaging:
   incoming:
     /device/location:
       topic: location
       connector: smallrye-kafka
       broadcast: true
     /device/status:
       topic: status
       connector: smallrye-kafka
       broadcast: true
     /device/canbus:
       topic: canbus
       connector: smallrye-kafka
       broadcast: true
keycloak:
  realm: external