quarkus:
  application:
    name: cerebral-stratum-backend
  devservices:
    enabled: true
  smallrye-openapi:
    path: /openapi
  swagger-ui:
    path: /swagger-ui
    always-include: true
  http:
    port: 6443
  grpc:
    server:
      port: 9000
      enable-reflection-service: true
      use-separate-server: false
  dev-ui:
    cors:
      enabled: false
  live-reload:
    instrumentation: true
  datasource:
    db-kind: postgresql
    devservices:
      db-name: cerebral-stratum
      init-script-path: devservices/init.sql
      port: 5432
      image-name: postgis/postgis:16-3.4
      command: postgres
      container-env:
        "POSTGRES_HOST_AUTH_METHOD": trust
  hibernate-orm:
    database:
      default-schema: ${quarkus.liquibase.default-schema-name}
    mapping:
      format:
        global: ignore
      timezone:
        default-storage: normalize-utc
    schema-management:
      strategy: none
  oidc:
    client-id: cerebral-stratum-backend
    roles:
        role-claim-path: realm_access/roles
  keycloak:
    devservices:
      enabled: true
      java-opts: -XX:UseSVE=0
      realm-path: devservices/realm.json
      realm-name: ${keycloak.realm}
    admin-client:
      realm: ${keycloak.realm}
    policy-enforcer:
     enabled: false
  scheduler:
    start-mode: normal
  kafka:
    devservices:
      port: 9092
'%prod':
  quarkus:
    otel:
      resource:
        attributes: "service.name=cerebral-stratum-backend,service.namespace=cerebral-stratum,deployment.environment=production"
      traces:
        enabled: true
        eusp:
          enabled: false
      logs:
        enabled: true
      metrics:
        enabled: true
    liquibase:
      migrate-at-start: true
      change-log: db/changeLog.yaml
      default-schema-name: cerebralstratum
    http:
      host: 0.0.0.0
      cors:
        enabled: true
        origins: /.*/
    datasource:
      jdbc:
        url: ${JDBC_URL:jdbc:postgresql://localhost:5432/cerebral-stratum}?defaultSchema=cerebralstratum
      username: ${JDBC_USERNAME:postgres}
      password: ${JDBC_PASSWORD}
    oidc:
      auth-server-url: ${OIDC_AUTH_SERVER_URL:https://sso.blueguardian.co/realms/external}
      credentials:
        secret: ${OIDC_SECRET}
    keycloak:
      admin-client:
        server-url: https://sso.blueguardian.co
        username: ${keycloak.username}
        password: ${keycloak.password}
        realm: ${keycloak.realm}
        grant-type: CLIENT_CREDENTIALS
        client-id: ${quarkus.oidc.client-id}
        client-secret: ${quarkus.oidc.credentials.secret}
      policy-enforcer:
        paths:
          quarkus-status:
            paths: /q/*
            enforcement-mode: disabled
          swagger-ui:
            paths: /swagger-ui/*
            enforcement-mode: disabled
          openapi:
            paths: /openapi
            enforcement-mode: disabled
        enabled: true
'%dev':
  quarkus:
    otel:
      resource:
        attributes: "service.name=cerebral-stratum-backend,service.namespace=${env:HOSTNAME},deployment.environment=development"
      traces:
        enabled: true
        eusp:
          enabled: true
      logs:
        enabled: true
      metrics:
        enabled: true
      exporter:
        otlp:
          endpoint: https://otlp-gateway-prod-au-southeast-1.grafana.net/otlp
          protocol: http/protobuf
    liquibase:
      migrate-at-start: true
      change-log: devservices/changeLog.yaml
      default-schema-name: cerebralstratum
    http:
      host: localhost
      cors:
        origins: /.*/
    oidc:
      credentials:
        secret: yxj6VJfZB8plW95iLkGn9ebWPPhic6yY
      client-id: cerebral-stratum-backend
    keycloak:
      admin-client:
        server-url: ${quarkus.oidc.auth-server-url}
        username: admin
        password: admin
        realm: ${keycloak.realm}
        grant-type: CLIENT_CREDENTIALS
        client-id: ${quarkus.oidc.client-id}
        client-secret: ${quarkus.oidc.credentials.secret}
keycloak:
  realm: external